[package]
name = "glr_core"
version.workspace = true
edition.workspace = true
authors.workspace = true

[lib]
crate-type = ["lib"]

[dependencies]
strum = { version = "0.26.3", features = ["derive"] }
strum_macros = "0.26.4"
serde = { version = "1.0.217", features = ["derive"] }
num_enum = "0.7.4"
